### ISSUE TITLE
Cuantificación de ruido por uso de grid cartesiana

### ISSUE THREAD

**Issue by sbustamante** [sbustamante/CosmicVoidsPaper#18]
**Sect 3.3, 2nd paragraph: I do not see why "the analysis of [y]our results" shows that a fixed Cartesian mesh does not induce spurious results". It's true, that the results look reasonable, but I think it would be better to state something about the level of discreteness noise, e.g. the number of zero-density cells, or the minimum if there are none.**

**Comment by sbustamante** [comment]
Sobre este item no entendí bien lo que debemos hacer.

**Comment by forero** [comment]
Listo. En este caso la idea era que las regiones de baja densidad podrian estar sampleadas con un numero muy bajo de particulas (i.e. celdas con cero particulas), haciendo que el campo de densidad fuera ruidoso.
