### ISSUE TITLE
Efecto de cambio de resolución

### ISSUE THREAD

**Issue by sbustamante** [sbustamante/CosmicVoidsPaper#21]
**All quantities are computed at the pixel scale, ~1 Mpc/h, correct? If the authors have any insights about how the results would change if this scale were changed, it would be helpful to state them. A quantitative discussion of how some results would change with a different scale would be great, but not necessary.**

**Comment by sbustamante** [comment]
Que opinas de esto? Esta es la parte que nos podría implicar más tiempo, ya que hay que calcular todo de nuevo y después mirar que tanto cambian los resultados.
En caso de que lo hagamos, podría ser con resolución de 512^3 (creo que la Tweb y Vweb ya la tienes para esas resoluciones), o podríamos hacerlo para 128^3 (Tienes estas resoluciones calculadas?)

Otra opción más sensata quizá, es justificar mejor porque la resolución de 1 Mpc/h es la adecuada para este estudio.

Me comentas que opinas.

**Comment by forero** [comment]
En este caso simplemente menciono lo que ha salido en otros papers sobre una smoothing scale mas grande. En resumen todo se acerca a lo que seria un gaussian random field.
