### ISSUE TITLE
Nueva figura de FA para cada entorno

### ISSUE THREAD

**Issue by sbustamante** [sbustamante/CosmicVoidsPaper#22]
Jaime, cree una figura nueva para ambos esquemas. Son simplemente las distribuciones de FA para las celdas de cada tipo de entorno. Lo pensé con el objetivo de convencer que efectivamente el valor de corte en FA para los vacíos produce sheets en las fronteras que son altamente anisotrópicos. Esto justifica la elección de FA=0.95 como razonable (óptima?) para definir bien las fronteras de vacíos.

Por ahora agregué la nueva figura como parte de la figura 2. Ahora ando pensando en el caption, pero no sé que te parece dejarla como parte de la figura 2, o crear una nueva figura con su propio caption.
Me comentas porfa que opinas, e inclusive si te parece bien la nueva figura.

**Comment by forero** [comment]
Hola, Estaba viendo la figura, y creo que es interesante, pero abre un problema nuevo. El problema es que la separacion de environments depende de lambda_th! En principio voy a quitarla, pero voy a releer el paper completo y veo si tal vez sea bueno dejarla.

**Comment by forero** [comment]
al final la deje!
