### ISSUE TITLE
Cambio Figura 3

### ISSUE THREAD

**Issue by forero** [sbustamante/CosmicVoidsPaper#3]
En la Figura 3 de abundancia de voids. Hay que:
1. Quitar lo de compensated y overcompensated, solamente dejar el total.
2. Dejar V-Web y T-Web como curvas de diferente tipo y no solamente color. Si se imprime a blanco y negro no se nota bien la diferencia.

**Comment by sbustamante** [comment]
Hecho! 
Ya no están las curvas para over y subcompensated voids. 
Tweb aparece como linea contínua y Vweb línea punteada.
