### ISSUE TITLE
Nueva Figura Overcompensated/compensated

### ISSUE THREAD

**Issue by forero** [sbustamante/CosmicVoidsPaper#4]
Preparar una nueva figura que muestre la fraccion de voids que son compensated/overcompensated como funcion de la masa.

**Comment by sbustamante** [comment]
Para la masa del vacío, se toma como la suma de las masas de las celdas miembro? O como la integral del stacked density profile de cada void?
Yo creería que los dos resultados deberían ser similares. Además, la última forma sale más directa. Que opinas?

**Comment by forero** [comment]
Agh. Me equivoque. No es la masa sino el radio efectivo.

**Comment by sbustamante** [comment]
Listo, nueva figura de número de voids (sub y overcompensated) vs radio efectivo.
