### ISSUE TITLE
Sobre formato en figura 2.

### ISSUE THREAD

**Issue by sbustamante** [sbustamante/CosmicVoidsPaper#5]
Es necesario cambiar el tipo de linea para la figura 2? En principio tendríamos el mismo problema que la figura de abundancias cuando se imprima en blanco y negro. Que opinas?

**Comment by forero** [comment]
Yo creo que si se deberia cambiar. Lo mismo en la Figura 4 de todos los perfiles. Ahi tal vez la mejor opcion ser cambiar el grosor de las lineas.

**Comment by sbustamante** [comment]
Formatos coregidos!
