### ISSUE TITLE
Figura 3

### ISSUE THREAD

**Issue by forero** [sbustamante/CosmicVoidsPaper#7]
La Figura 3 que describo en el paper es la que estaba antes con las fracciones en funcion del radio (algo inmediato de interpretar). Pero no le puedo encontrar sentido a la fraccion acumulada en funcion del radio.  Por ejemplo que significa que a r_eff=3.2 una (C<1 Tweb) sea 0.25 y la otra (C>1 Tweb) sea 0.17?

**Comment by sbustamante** [comment]
Para la fracción acumulada, en el caso que dices, 0.17 a r_eff=3.2 para Tweb y C>1 significa que el 17% de todos los vacíos son sobrecompensados y tienen un radio efectivo de al menos 3.2 Mpc. 

Otro caso interesante sería los vacíos subcompensados (C<1) de la Vweb. De la curva gruesa azul se puede ver que 50% de todos los vacíos encontrados en Vweb son subcompensados con un radio menor a 2.8Mpc aproximadamente (esto corresponde a los spurious voids que se mencionan).

Para el máximo radio efectivo recuperamos las fracciones totales que se mencionan. Para Tweb se tendrían 65% de todos los voids subcompensados y 35% sobrecompensados. Para la Vweb tenemos 85% subcompensados y 15% sobrecompensados.

De todas maneras voy a montar las dos figuras:
voids_regions_volume_compensated.pdf
voids_regions_volume_compensated2.pdf

Yo no tengo problema con ninguna de las dos, me parecen bien ambas. Sin embargo, si el análsis ya está con la que estaba antes, entonces dejemos esa!

**Comment by forero** [comment]
Mi problema con tu figura es que mezcla dos informaciones diferentes: la distribucion en radio y la fraccion de overcompensated/subcompensanted. 
Prefiero la otra porque es mas facil de leer. Solamente incluye la informacion de la fraccion y quita la informacion de la distribucion.

Voy a dejar entones la que estaba antes.
