### ISSUE TITLE
Figura 3 (otra vez)

### ISSUE THREAD

**Issue by forero** [sbustamante/CosmicVoidsPaper#8]
En la Figura 3 a la izquierda, solamente se deberian toamr en cuenta los voids con radio mayor que 1Mpc que es lo que corresponde al smoothing lenght.

Igual a la derecha, la linea va desde un radio efectivo de cero (!?).

**Comment by sbustamante** [comment]
Listo, corregido!
El problema es que el bineo lo hacía desde 0 y graficaba con el valor de la izquierda. Yo corregí haciendo el bineo desde 1Mpc.
