### ISSUE TITLE
numero de voids

### ISSUE THREAD

**Issue by forero** [sbustamante/CosmicVoidsPaper#9]
Elgun lugar hace falta una tabla (o label en una grafica) con los numeros de voids en cada sample (sub y overcompensated) y en cada bin de radio efectivo que se usa en el calculo de los profiles.

**Comment by sbustamante** [comment]
Listo, tabla hecha!

Estan los números para cada bin de radio efectivo y el total de voids para cada sample (sub y overcompensated).
